# Generated by Django 4.2.4 on 2025-08-12 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_referralearning_referral_referalearningtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='reward_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referralearning',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
