# Generated by Django 4.2.4 on 2025-08-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
    ]
