# Generated by Django 4.2.4 on 2025-08-14 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_documenttype_proofofidentity_proofofaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofaddress',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.documenttype'),
        ),
        migrations.AlterField(
            model_name='proofofidentity',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.documenttype'),
        ),
    ]
