# Generated by Django 4.2.4 on 2025-08-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_proofofaddress_document_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proofofaddress',
            old_name='document_file',
            new_name='document_file_back',
        ),
        migrations.RenameField(
            model_name='proofofidentity',
            old_name='document_file',
            new_name='document_file_back',
        ),
        migrations.AddField(
            model_name='proofofaddress',
            name='document_file_front',
            field=models.FileField(default='ioksksm', upload_to='kyc/address/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proofofidentity',
            name='document_file_front',
            field=models.FileField(default='sijss', upload_to='kyc/identity/'),
            preserve_default=False,
        ),
    ]
