# Generated by Django 4.2.4 on 2025-08-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_proofofaddress_user_alter_proofofidentity_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proofofaddress',
            old_name='document_file_back',
            new_name='document_file',
        ),
        migrations.RemoveField(
            model_name='proofofaddress',
            name='document_file_front',
        ),
        migrations.AddField(
            model_name='proofofaddress',
            name='address_type',
            field=models.CharField(choices=[('home_address_1', 'Home Address 1'), ('home_address_2', 'Home Address 2')], default='home_address_1', max_length=20),
            preserve_default=False,
        ),
    ]
