# Generated by Django 4.2.4 on 2025-08-14 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_rename_document_file_back_proofofaddress_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofaddress',
            name='document_file',
            field=models.FileField(upload_to='static/kyc/address/'),
        ),
        migrations.AlterField(
            model_name='proofofaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proofofidentity',
            name='document_file_back',
            field=models.FileField(upload_to='static/kyc/identity/'),
        ),
        migrations.AlterField(
            model_name='proofofidentity',
            name='document_file_front',
            field=models.FileField(upload_to='static/kyc/identity/'),
        ),
    ]
