# Generated by Django 4.2.4 on 2025-08-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_is_2fa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
