# Generated by Django 4.2.4 on 2025-09-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_ticket_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
