# Generated by Django 4.2.4 on 2025-09-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_ticket_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default=123, editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
