# Generated by Django 4.2.4 on 2025-10-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_newslettersubscriber_unsubscribed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_email_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
