# Generated by Django 4.2.4 on 2025-08-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
