# Generated by Django 4.2.4 on 2025-08-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_propfirmchallenge_refundable_fee'),
        ('trading', '0002_tradingaccount_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.propfirmchallenge'),
        ),
    ]
