# Generated by Django 4.2.4 on 2025-08-01 20:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_tradingaccount_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='size',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
