# Generated by Django 4.2.4 on 2025-08-04 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_tradingaccount_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingaccount',
            name='selected',
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='selected_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
