# Generated by Django 4.2.4 on 2025-08-04 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_remove_tradingaccount_selected_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradingaccount',
            options={'ordering': ['-created_at', '-selected_date']},
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='selected_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
