# Generated by Django 4.2.4 on 2025-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_mt5account_mt5deal_mt5order_mt5orderhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5user',
            name='last_access',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mt5user',
            name='last_pass_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mt5user',
            name='registration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
