# Generated by Django 4.2.4 on 2025-08-26 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_propfirmchallenge_refundable_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0009_mt5user_last_access_mt5user_last_pass_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5account',
            name='account_type',
            field=models.CharField(choices=[('challenge', 'Challenge Account'), ('funded', 'Funded Account'), ('live', 'Live Account')], default='challenge', max_length=20),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.propfirmchallenge'),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='fail_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('challenge_passed', 'Challenge Passed'), ('expired', 'Expired'), ('failed', 'Failed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='mt5user',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
