# Generated by Django 4.2.4 on 2025-08-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_mt5account_account_type_mt5account_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5user',
            name='server',
            field=models.CharField(default='CommoT-Live', max_length=255),
        ),
    ]
