# Generated by Django 4.2.4 on 2025-08-27 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_propfirmchallenge_refundable_fee'),
        ('trading', '0011_mt5user_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mt5account',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='mt5account',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='mt5account',
            name='fail_reason',
        ),
        migrations.RemoveField(
            model_name='mt5account',
            name='status',
        ),
        migrations.AddField(
            model_name='mt5user',
            name='account_type',
            field=models.CharField(choices=[('challenge', 'Challenge Account'), ('funded', 'Funded Account'), ('live', 'Live Account')], default='challenge', max_length=20),
        ),
        migrations.AddField(
            model_name='mt5user',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.propfirmchallenge'),
        ),
        migrations.AddField(
            model_name='mt5user',
            name='fail_reason',
            field=models.TextField(blank=True),
        ),
    ]
