# Generated by Django 4.2.4 on 2025-08-27 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_remove_mt5account_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5user',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mt5user',
            name='selected_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
