# Generated by Django 4.2.4 on 2025-08-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_mt5user_password_mt5user_selected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('challenge_passed', 'Challenge Passed'), ('expired', 'Expired'), ('failed', 'Failed')], default='active', max_length=20),
        ),
    ]
