# Generated by Django 4.2.4 on 2025-09-01 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_mt5user_account_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MT5AccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.BigIntegerField(db_index=True, unique=True)),
                ('currency_digits', models.IntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('margin_free', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('margin_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margin_leverage', models.IntegerField(default=0)),
                ('margin_initial', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('margin_maintenance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('storage', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('floating', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('equity', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('so_activation', models.IntegerField(blank=True, default=0, null=True)),
                ('so_time', models.BigIntegerField(blank=True, null=True)),
                ('so_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('so_equity', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('so_margin', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('blocked_commission', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('blocked_profit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('assets', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('violation', 'Violation'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('auto_closed', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('trade_data', models.JSONField(blank=True, null=True)),
                ('account_state', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.mt5user')),
            ],
            options={
                'db_table': 'rule_violations',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['account', 'timestamp'], name='rule_violat_account_1a4968_idx'), models.Index(fields=['violation_type'], name='rule_violat_violati_e9d54e_idx'), models.Index(fields=['severity'], name='rule_violat_severit_5fb946_idx')],
            },
        ),
    ]
