# Generated by Django 4.2.4 on 2025-09-01 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_mt5accounthistory_ruleviolationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('bid', models.FloatField()),
                ('ask', models.FloatField()),
                ('last', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
