# Generated by Django 4.2.4 on 2025-09-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_symbolprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountactivity',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountactivity',
            name='related_trade',
        ),
        migrations.AlterUniqueTogether(
            name='dailyaccountstats',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailyaccountstats',
            name='account',
        ),
        migrations.AlterUniqueTogether(
            name='trade',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trade',
            name='account',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='ruleviolationlog',
            name='rule_violat_account_1a4968_idx',
        ),
        migrations.RemoveField(
            model_name='ruleviolationlog',
            name='account',
        ),
        migrations.AddField(
            model_name='ruleviolationlog',
            name='login',
            field=models.BigIntegerField(default=1045),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='ruleviolationlog',
            index=models.Index(fields=['login', 'timestamp'], name='rule_violat_login_96cec9_idx'),
        ),
        migrations.DeleteModel(
            name='AccountActivity',
        ),
        migrations.DeleteModel(
            name='DailyAccountStats',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.DeleteModel(
            name='TradingAccount',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
