# Generated by Django 4.2.4 on 2025-09-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_remove_accountactivity_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt5deal',
            name='gateway',
            field=models.CharField(blank=True, null=True),
        ),
    ]
