# Generated by Django 4.2.4 on 2025-09-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0018_alter_mt5deal_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5position',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
