# Generated by Django 4.2.4 on 2025-09-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0019_mt5position_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5daily',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
