# Generated by Django 4.2.4 on 2025-09-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_mt5daily_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5deal',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ruleviolationlog',
            name='severity',
            field=models.CharField(choices=[('warning', 'Warning'), ('severe', 'Severe'), ('critical', 'Critical')], max_length=20),
        ),
    ]
