# Generated by Django 4.2.4 on 2025-09-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0021_mt5deal_deleted_alter_ruleviolationlog_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.BigIntegerField(db_index=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
