# Generated by Django 4.2.4 on 2025-09-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0022_accountearnings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountearnings',
            old_name='amount',
            new_name='disbursed',
        ),
        migrations.RenameField(
            model_name='accountearnings',
            old_name='paid',
            new_name='paid_all',
        ),
        migrations.AddField(
            model_name='accountearnings',
            name='pending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='accountearnings',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
