# Generated by Django 4.2.4 on 2025-09-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0023_rename_amount_accountearnings_disbursed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt5accounthistory',
            name='login',
            field=models.BigIntegerField(),
        ),
    ]
