# Generated by Django 4.2.4 on 2025-09-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0024_alter_mt5accounthistory_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5account',
            name='prev_equity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='prev_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='prev_margin_free',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
