# Generated by Django 4.2.4 on 2025-09-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0025_mt5account_prev_equity_mt5account_prev_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountearnings',
            name='target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
