# Generated by Django 4.2.4 on 2025-09-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0026_accountearnings_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5account',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
