# Generated by Django 4.2.4 on 2025-09-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0027_mt5account_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDrawdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.BigIntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('equity_high', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('equity_low', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('drawdown_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('login', 'date')},
            },
        ),
    ]
