# Generated by Django 4.2.4 on 2025-09-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0028_accountdrawdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTotalDrawdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.BigIntegerField(db_index=True, unique=True)),
                ('equity_peak', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('equity_low', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('drawdown_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
