# Generated by Django 4.2.4 on 2025-09-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0030_mt5account_mt5_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountWatermarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.BigIntegerField(db_index=True, unique=True)),
                ('hwm_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('hwm_equity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lwm_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lwm_equity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('hwm_date', models.DateTimeField()),
                ('lwm_date', models.DateTimeField()),
            ],
        ),
    ]
