# Generated by Django 4.2.4 on 2025-09-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0032_mt5user_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mt5user',
            name='step',
        ),
        migrations.AddField(
            model_name='mt5account',
            name='step',
            field=models.IntegerField(default=1),
        ),
    ]
