# Generated by Django 4.2.4 on 2025-09-09 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0033_remove_mt5user_step_mt5account_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5account',
            name='challenge_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='challenge_completion_date',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='challenge_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='challenge_failure_date',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='failure_reason',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='is_funded_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='phase_2_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mt5account',
            name='mt5_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='trading.mt5user'),
        ),
        migrations.CreateModel(
            name='ChallengeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.mt5user')),
            ],
        ),
    ]
