# Generated by Django 4.2.4 on 2025-09-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0034_mt5account_challenge_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5user',
            name='funded_account_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FundedAccountIssued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.mt5user')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.mt5account')),
            ],
        ),
    ]
