# Generated by Django 4.2.4 on 2025-09-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0035_mt5user_funded_account_issued_fundedaccountissued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mt5account',
            name='challenge_failure_date',
        ),
    ]
