# Generated by Django 4.2.4 on 2025-09-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0036_remove_mt5account_challenge_failure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5account',
            name='challenge_failure_date',
            field=models.DateTimeField(null=True),
        ),
    ]
