# Generated by Django 4.2.4 on 2025-09-24 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0037_mt5account_challenge_failure_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('stars', models.IntegerField(default=0)),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mt5_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='trading.mt5user')),
            ],
        ),
    ]
