# Generated by Django 4.2.4 on 2025-09-30 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0016_competition_price_pool_cash_alter_competition_uuid'),
        ('trading', '0038_accountrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5user',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.competition'),
        ),
        migrations.AlterField(
            model_name='mt5user',
            name='account_type',
            field=models.CharField(choices=[('challenge', 'Challenge Account'), ('funded', 'Funded Account'), ('live', 'Live Account'), ('competition', 'Competition')], default='challenge', max_length=20),
        ),
    ]
