# Generated by Django 4.2.4 on 2025-10-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0039_mt5user_competition_alter_mt5user_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountwatermarks',
            name='hwm_date',
        ),
        migrations.RemoveField(
            model_name='accountwatermarks',
            name='lwm_date',
        ),
    ]
