# Generated by Django 4.2.4 on 2025-10-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0040_remove_accountwatermarks_hwm_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5account',
            name='funded',
            field=models.BooleanField(default=False),
        ),
    ]
