# Generated by Django 4.2.4 on 2025-10-17 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0041_mt5account_funded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mt5user',
            old_name='funded_account_issued',
            new_name='funded',
        ),
    ]
