# Generated by Django 4.2.4 on 2025-10-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0042_rename_funded_account_issued_mt5user_funded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountdrawdown',
            options={'get_latest_by': 'created_at'},
        ),
    ]
