# Generated by Django 4.2.4 on 2025-10-23 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0022_competitionresult_losing_trades_and_more'),
        ('trading', '0043_alter_accountdrawdown_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt5user',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.competition'),
        ),
        migrations.AlterField(
            model_name='mt5user',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
