# Generated by Django 4.2.4 on 2025-10-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0044_alter_mt5user_competition_alter_mt5user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5user',
            name='refundable_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
