# Generated by Django 4.2.4 on 2025-10-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0045_mt5user_refundable_fee_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5user',
            name='refundable_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
