# Generated by Django 4.2.4 on 2025-08-02 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('order_description', models.TextField()),
                ('price_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_currency', models.CharField(default='USD', max_length=10)),
                ('pay_currency', models.CharField(max_length=10)),
                ('pay_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('pay_address', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('waiting', 'Waiting'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('sending', 'Sending'), ('partially_paid', 'Partially Paid'), ('finished', 'Finished'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
