# Generated by Django 4.2.4 on 2025-08-15 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropFirmWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('withdrawal_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propfirm_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropFirmWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('payout_currency', models.CharField(help_text='e.g. USDT, BTC, ETH', max_length=10)),
                ('payout_network', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum ERC20'), ('TRX', 'Tron TRC20'), ('BSC', 'Binance Smart Chain BEP20'), ('SOL', 'Solana'), ('OTHER', 'Other')], max_length=10)),
                ('payout_wallet_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.propfirmwallet')),
            ],
        ),
    ]
