# Generated by Django 4.2.4 on 2025-08-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_propfirmwallet_propfirmwallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='propfirmwallettransaction',
            name='type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propfirmwallettransaction',
            name='payout_currency',
            field=models.CharField(blank=True, help_text='e.g. USDT, BTC, ETH', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='propfirmwallettransaction',
            name='payout_network',
            field=models.CharField(blank=True, choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum ERC20'), ('TRX', 'Tron TRC20'), ('BSC', 'Binance Smart Chain BEP20'), ('SOL', 'Solana'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='propfirmwallettransaction',
            name='payout_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
