# Generated by Django 4.2.4 on 2025-08-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_propfirmwallettransaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propfirmwallettransaction',
            name='currency_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
