# Generated by Django 4.2.4 on 2025-08-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_propfirmwallettransaction_currency_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propfirmwallettransaction',
            old_name='payout_wallet_address',
            new_name='pay_address',
        ),
        migrations.RenameField(
            model_name='propfirmwallettransaction',
            old_name='payout_currency',
            new_name='pay_currency',
        ),
        migrations.RenameField(
            model_name='propfirmwallettransaction',
            old_name='payout_network',
            new_name='pay_network',
        ),
        migrations.RemoveField(
            model_name='propfirmwallettransaction',
            name='requested_amount',
        ),
        migrations.AddField(
            model_name='propfirmwallettransaction',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='propfirmwallettransaction',
            name='pay_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='propfirmwallettransaction',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
