# Generated by Django 4.2.4 on 2025-08-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_payout_wallet_address_propfirmwallettransaction_pay_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propfirmwallettransaction',
            name='price_amount',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='propfirmwallettransaction',
            name='price_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
