# Generated by Django 4.2.4 on 2025-08-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_propfirmwallettransaction_price_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propfirmwallettransaction',
            name='order_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
