# Generated by Django 4.2.4 on 2025-08-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_propfirmwallettransaction_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propfirmwallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
