# Generated by Django 4.2.4 on 2025-09-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_propfirmwallettransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='login',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
