# Generated by Django 4.2.4 on 2025-09-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_payment_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='login',
        ),
        migrations.AddField(
            model_name='propfirmwallettransaction',
            name='login',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
