# Generated by Django 4.2.4 on 2025-10-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_remove_payment_login_propfirmwallettransaction_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propfirmwallet',
            name='disbursed_amount',
        ),
        migrations.RemoveField(
            model_name='propfirmwallet',
            name='pending_amount',
        ),
        migrations.RemoveField(
            model_name='propfirmwallet',
            name='withdrawal_profit',
        ),
        migrations.AddField(
            model_name='propfirmwallet',
            name='pay_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propfirmwallet',
            name='pay_currency',
            field=models.CharField(blank=True, help_text='e.g. USDT, BTC, ETH', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='propfirmwallet',
            name='pay_network',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
