# Generated by Django 4.2.4 on 2025-10-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_withdrawalrequest_propfirmwallet_currency_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='disbursed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
