# Generated by Django 4.2.4 on 2025-10-21 09:15

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_withdrawalrequest_disbursed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='withdrawal_id',
            field=models.CharField(default=payment.models.generate_withdrawal_id, editable=False, max_length=20, unique=True),
        ),
    ]
