# Generated by Django 4.2.4 on 2025-10-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_withdrawalrequest_withdrawal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='currency_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='pay_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='pay_currency',
            field=models.CharField(blank=True, help_text='e.g. USDT, BTC, ETH', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='pay_network',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
