# Generated by Django 4.2.4 on 2025-07-31 08:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropFirmChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('firm_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('one_step', 'One Step'), ('two_step', 'Two Step'), ('instant', 'Instant Funding')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('coming_soon', 'Coming Soon'), ('ended', 'Ended')], default='active', max_length=20)),
                ('account_size', models.DecimalField(decimal_places=2, max_digits=12)),
                ('challenge_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_split_percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_daily_loss_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_total_loss_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit_target_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_trading_days', models.IntegerField()),
                ('max_trading_days', models.IntegerField(blank=True, null=True)),
                ('consistency_rule_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weekend_holding', models.BooleanField(default=True)),
                ('news_trading_allowed', models.BooleanField(default=True)),
                ('ea_allowed', models.BooleanField(default=True)),
                ('copy_trading_allowed', models.BooleanField(default=False)),
                ('allowed_instruments', models.CharField(choices=[('forex', 'Forex'), ('indices', 'Indices'), ('commodities', 'Commodities'), ('crypto', 'Crypto'), ('all', 'All Instruments')], default='all', max_length=20)),
                ('duration_days', models.IntegerField()),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('current_participants', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'propfirm_challenges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['firm_name'], name='propfirm_ch_firm_na_f57a9f_idx'), models.Index(fields=['status'], name='propfirm_ch_status_24508f_idx'), models.Index(fields=['challenge_type'], name='propfirm_ch_challen_5564f2_idx'), models.Index(fields=['account_size'], name='propfirm_ch_account_6baf27_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('forex', 'Forex'), ('indices', 'Indices'), ('commodities', 'Commodities'), ('crypto', 'Crypto'), ('all', 'All Instruments')], max_length=20)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='challenge.propfirmchallenge')),
            ],
            options={
                'unique_together': {('challenge', 'instrument')},
            },
        ),
    ]
