# Generated by Django 4.2.4 on 2025-08-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_propfirmchallenge_refundable_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='propfirmchallenge',
            name='challenge_class',
            field=models.CharField(choices=[('challenge', 'Challenge'), ('skill_check', 'Skill check')], default='challenge', max_length=255),
        ),
    ]
