# Generated by Django 4.2.4 on 2025-09-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_propfirmchallenge_challenge_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='propfirmchallenge',
            name='cross_account_hedging_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='grid_trading_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='hedging_within_account_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='latency_arbitrage_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='market_making_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='martingale_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='max_inactive_days_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='max_orders_per_symbol',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='max_risk_per_trade_percent',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='max_trades_per_hour',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='max_trades_per_minute',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='min_trade_duration_seconds',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='overall_risk_limit_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='statistical_arbitrage_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='stop_loss_required',
            field=models.BooleanField(default=False),
        ),
    ]
