# Generated by Django 4.2.4 on 2025-09-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_propfirmchallenge_cross_account_hedging_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propfirmchallenge',
            name='additional_trading_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='phase_2_max_trading_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='phase_2_min_trading_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='phase_2_profit_target_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
    ]
