# Generated by Django 4.2.4 on 2025-09-08 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0005_propfirmchallenge_additional_trading_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_class', models.CharField(choices=[('challenge', 'Challenge'), ('skill_check', 'Skill check')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('account_size', models.BigIntegerField()),
                ('profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ChallengeInstrument',
        ),
    ]
