# Generated by Django 4.2.4 on 2025-09-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_challengecertificate_delete_challengeinstrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='propfirmchallenge',
            name='additional_phase_total_loss_percent',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=5),
        ),
    ]
