# Generated by Django 4.2.4 on 2025-09-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_propfirmchallenge_additional_phase_total_loss_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propfirmchallenge',
            name='challenge_class',
            field=models.CharField(choices=[('challenge', 'Challenge'), ('challenge_funding', 'Challenge Funding'), ('skill_check', 'Skill check'), ('skill_check_funding', 'Skill Check Funding')], default='challenge', max_length=255),
        ),
        migrations.AlterField(
            model_name='propfirmchallenge',
            name='challenge_type',
            field=models.CharField(choices=[('one_step', 'One Step'), ('two_step', 'Two Step'), ('instant', 'Funding')], max_length=20),
        ),
    ]
