# Generated by Django 4.2.4 on 2025-09-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_alter_propfirmchallenge_challenge_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengecertificate',
            name='login',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
