# Generated by Django 4.2.4 on 2025-09-18 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_challengecertificate_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengecertificate',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
