# Generated by Django 4.2.4 on 2025-09-30 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_challengecertificate_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('starting_balance', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, help_text='Percentage e.g. 5.00 = 5%', max_digits=5)),
                ('max_total_drawdown', models.DecimalField(decimal_places=2, help_text='Percentage e.g. 10.00 = 10%', max_digits=5)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('prize_structure', models.JSONField(default=dict, help_text='Example: {"1": 5000, "2": 3000, "3": 2000}')),
            ],
        ),
        migrations.AlterField(
            model_name='propfirmchallenge',
            name='challenge_class',
            field=models.CharField(choices=[('challenge', 'Challenge'), ('challenge_funding', 'Challenge Funding'), ('skill_check', 'Skill check'), ('skill_check_funding', 'Skill Check Funding'), ('competition', 'Competition')], default='challenge', max_length=255),
        ),
        migrations.AddField(
            model_name='propfirmchallenge',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.competition'),
        ),
    ]
