# Generated by Django 4.2.4 on 2025-09-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0011_competition_alter_propfirmchallenge_challenge_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propfirmchallenge',
            name='competition',
        ),
    ]
