# Generated by Django 4.2.4 on 2025-09-30 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0012_remove_propfirmchallenge_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='propfirmchallenge',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.competition'),
        ),
    ]
