# Generated by Django 4.2.4 on 2025-09-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0013_propfirmchallenge_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
