# Generated by Django 4.2.4 on 2025-09-30 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0014_competition_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
