# Generated by Django 4.2.4 on 2025-09-30 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0015_alter_competition_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='price_pool_cash',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='competition',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
