# Generated by Django 4.2.4 on 2025-10-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0016_competition_price_pool_cash_alter_competition_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_uuid', models.CharField(db_index=True, max_length=100)),
                ('login', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('starting_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('final_equity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('return_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_drawdown', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_trades', models.IntegerField()),
                ('winning_trades', models.IntegerField()),
                ('win_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score', models.FloatField()),
                ('finalized_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['competition_uuid', 'rank'],
                'indexes': [models.Index(fields=['competition_uuid', 'rank'], name='challenge_c_competi_a8c3c6_idx')],
                'unique_together': {('competition_uuid', 'login')},
            },
        ),
    ]
