# Generated by Django 4.2.4 on 2025-10-12 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0017_competition_ended_competition_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propfirmchallenge',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.competition'),
        ),
    ]
