# Generated by Django 4.2.4 on 2025-10-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0018_alter_propfirmchallenge_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
