# Generated by Django 4.2.4 on 2025-10-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0020_alter_competition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='max_daily_loss',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage e.g. 5.00 = 5%', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='max_total_drawdown',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage e.g. 10.00 = 10%', max_digits=5, null=True),
        ),
    ]
