# Generated by Django 4.2.4 on 2025-10-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0021_alter_competition_max_daily_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionresult',
            name='losing_trades',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propfirmchallenge',
            name='challenge_class',
            field=models.CharField(choices=[('challenge', 'Challenge'), ('skill_check', 'Skill check'), ('competition', 'Competition')], default='challenge', max_length=255),
        ),
    ]
